server:
  rest:
    listenAddress: "localhost"
    port: 8081
    enableSwagger: true
    defaultTimeout: 10000
    readTimeout: 10000
    writeTimeout: 10000
    APIKey: "123456"

rdbms:
  app:
    dsn: "postgres://postgres:password@localhost:5432/waizlytest?sslmode=disable"
    driver: postgres
    maxOpenConns: 10
    maxIdleConns: 10
    connMaxLifetime: 3000
    retry: 3
  
dbmigrate:
  app:
    dsn: "postgres://postgres:password@localhost:5432/waizlytest?sslmode=disable"
    driver: postgres

tracer:
  jaeger:
    collectorUrl: "http://localhost:14268/api/traces"

authConfig:
  enableBasicAuth: true
  username: fudjie
  password: password